ТЗ спринта 10
ikarus-stv/java-filmorate pull request #2
Opened 2024-08-09 13:05 UTC by ikarus-stv

2024-08-10 04:43 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        long currentMaxId = films.keySet()
Отлично, что пользуешься стримами. Надеюсь здесь понятно, что на реально больших данных последовательный перебор для поиска максимального значения, будет не оптимален по производительности. И решением было бы просто завести поле со счетчиком идентификаторов.

2024-08-10 04:46 UTC, VadimZharkov requested changes
Можно улучшить

2024-08-11 18:03 UTC, ikarus-stv commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        long currentMaxId = films.keySet()
Завел поле со счетчиком идентификаторов, перебор убрал

2024-08-12 05:05 UTC, VadimZharkov approved these changes

2024-08-12 05:05 UTC, VadimZharkov approved these changes

2024-08-12 17:07 UTC, merged